# Ruby program to illustrate hwo to
# escape the exception

#!/usr/bin/ruby

threads = []

5.times do |value|
	threads << Thread.new(value) do |a|
		raise "oops error!" if a == 3
print "#{a}\n"
end

end

threads.each do |x|
begin

x.join

# using rescue method
rescue RuntimeError => y
	puts "Failed:: #{y.message}"
end
end
